[package]
name = "untitled"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
error-chain = "0.12.4"
regex = "1.10.3"
reqwest = "0.11.24"
tokio = { version = "1.36.0", features = ["full"] }
